/* Rule id -> page anchor, and the helpers that turn a rule mention into a
   link. The map between the markers below is generated by
   scripts/generate_rules_map.py from the catalog in trustsight.categories,
   the same source the rules reference is built from; `npm run build` fails
   when the two disagree. Everything outside the markers is hand-written. */

/* rules-map:start */
export const RULE_PAGES = {
  c001: 'integrity/#c001',
  c002: 'integrity/#c002',
  c003: 'integrity/#c003',
  c004: 'integrity/#c004',
  c005: 'integrity/#c005',
  c006: 'maintainer-and-metadata/#c006',
  c007: 'fetch-and-execution/#c007',
  c008: 'integrity/#c008',
  c009: 'integrity/#c009',
  d001: 'naming-and-dependency/#d001',
  d002: 'naming-and-dependency/#d002',
  d003: 'naming-and-dependency/#d003',
  d004: 'naming-and-dependency/#d004',
  h001: 'integrity/#h001',
  h002: 'integrity/#h002',
  h003: 'fetch-and-execution/#h003',
  h004: 'fetch-and-execution/#h004',
  h005: 'integrity/#h005',
  h006: 'naming-and-dependency/#h006',
  h007: 'staging-and-recon/#h007',
  h008: 'integrity/#h008',
  h009: 'fetch-and-execution/#h009',
  h010: 'staging-and-recon/#h010',
  h011: 'fetch-and-execution/#h011',
  h012: 'deception/#h012',
  h013: 'deception/#h013',
  h014: 'obfuscation/#h014',
  h015: 'fetch-and-execution/#h015',
  h016: 'fetch-and-execution/#h016',
  h017: 'install-and-persist/#h017',
  h018: 'integrity/#h018',
  h019: 'integrity/#h019',
  h020: 'temporal/#h020',
  h021: 'temporal/#h021',
  h022: 'temporal/#h022',
  h023: 'install-and-persist/#h023',
  h024: 'integrity/#h024',
  h025: 'integrity/#h025',
  h026: 'maintainer-and-metadata/#h026',
  h027: 'composition/#h027',
  h028: 'corpus-behavioral/#h028',
  h029: 'naming-and-dependency/#h029',
  h030: 'count-based/#h030',
  h031: 'fetch-and-execution/#h031',
  h032: 'install-and-persist/#h032',
  h033: 'integrity/#h033',
  h034: 'fetch-and-execution/#h034',
  h035: 'install-and-persist/#h035',
  h036: 'count-based/#h036',
  h037: 'maintainer-and-metadata/#h037',
  h038: 'staging-and-recon/#h038',
  h039: 'install-and-persist/#h039',
  h040: 'staging-and-recon/#h040',
  h041: 'fetch-and-execution/#h041',
  h042: 'staging-and-recon/#h042',
  h043: 'composition/#h043',
  h044: 'maintainer-and-metadata/#h044',
  h045: 'count-based/#h045',
  h046: 'corpus-behavioral/#h046',
  h047: 'integrity/#h047',
  h048: 'naming-and-dependency/#h048',
  h049: 'maintainer-and-metadata/#h049',
  h050: 'maintainer-and-metadata/#h050',
  h051: 'maintainer-and-metadata/#h051',
  h052: 'count-based/#h052',
  h053: 'naming-and-dependency/#h053',
  h054: 'maintainer-and-metadata/#h054',
  h055: 'count-based/#h055',
  h056: 'corpus-behavioral/#h056',
  h057: 'corpus-behavioral/#h057',
  h058: 'maintainer-and-metadata/#h058',
  h059: 'naming-and-dependency/#h059',
  h060: 'corpus-behavioral/#h060',
  h061: 'corpus-behavioral/#h061',
  h062: 'install-and-persist/#h062',
  h063: 'maintainer-and-metadata/#h063',
  h064: 'naming-and-dependency/#h064',
  h065: 'obfuscation/#h065',
  h066: 'integrity/#h066',
  h067: 'deception/#h067',
  h068: 'fetch-and-execution/#h068',
  h069: 'fetch-and-execution/#h069',
  h070: 'integrity/#h070',
  h071: 'fetch-and-execution/#h071',
  h072: 'fetch-and-execution/#h072',
  h073: 'corpus-behavioral/#h073',
  h074: 'maintainer-and-metadata/#h074',
  h075: 'fetch-and-execution/#h075',
  h076: 'staging-and-recon/#h076',
  h077: 'fetch-and-execution/#h077',
  h078: 'integrity/#h078',
  h079: 'integrity/#h079',
  h080: 'obfuscation/#h080',
  h081: 'fetch-and-execution/#h081',
  h082: 'fetch-and-execution/#h082',
  h083: 'fetch-and-execution/#h083',
  h084: 'install-and-persist/#h084',
  h085: 'staging-and-recon/#h085',
  h086: 'maintainer-and-metadata/#h086',
  h087: 'integrity/#h087',
  h088: 'maintainer-and-metadata/#h088',
  h089: 'install-and-persist/#h089',
  h090: 'fetch-and-execution/#h090',
  h091: 'integrity/#h091',
  h092: 'integrity/#h092',
  h093: 'install-and-persist/#h093',
  h094: 'fetch-and-execution/#h094',
  h095: 'install-and-persist/#h095',
  h096: 'integrity/#h096',
  h097: 'integrity/#h097',
  p001: 'system/#declared-practice',
  p002: 'system/#declared-practice',
  p003: 'system/#declared-practice',
  p005: 'system/#declared-practice',
  p006: 'system/#declared-practice',
  p007: 'system/#declared-practice',
  p008: 'system/#declared-practice',
  r001: 'fetch-and-execution/#r001',
  r002: 'fetch-and-execution/#r002',
  r003: 'obfuscation/#r003',
  r007: 'install-and-persist/#r007',
  r008: 'fetch-and-execution/#r008',
  r010: 'fetch-and-execution/#r010',
  r011: 'fetch-and-execution/#r011',
  r012: 'deception/#r012',
  r013: 'deception/#r013',
  r017: 'install-and-persist/#r017',
  r039: 'obfuscation/#r039',
  r040: 'obfuscation/#r040',
  r041: 'fetch-and-execution/#r041',
  r042: 'fetch-and-execution/#r042',
  r043: 'obfuscation/#r043',
  r044: 'fetch-and-execution/#r044',
  r045: 'obfuscation/#r045',
  r046: 'fetch-and-execution/#r046',
  r047: 'fetch-and-execution/#r047',
  r048: 'fetch-and-execution/#r048',
  r049: 'integrity/#r049',
  r050: 'integrity/#r050',
  r051: 'fetch-and-execution/#r051',
  r052: 'install-and-persist/#r052',
  r053: 'install-and-persist/#r053',
  r054: 'install-and-persist/#r054',
  r055: 'fetch-and-execution/#r055',
  r056: 'fetch-and-execution/#r056',
  r057: 'fetch-and-execution/#r057',
  r058: 'staging-and-recon/#r058',
  r059: 'install-and-persist/#r059',
  r078: 'integrity/#r078',
  r091: 'integrity/#r091',
  r099: 'integrity/#r099',
  r104: 'integrity/#r104',
  r144: 'install-and-persist/#r144',
  s001: 'sabotage/#s001',
  s002: 'sabotage/#s002',
  s003: 'sabotage/#s003',
  s004: 'sabotage/#s004',
  s005: 'sabotage/#s005',
  s006: 'sabotage/#s006',
  s007: 'sabotage/#s007',
  s008: 'sabotage/#s008',
  w001: 'unverifiable/#w001',
  w002: 'unverifiable/#w002',
  w003: 'unverifiable/#w003',
  w004: 'unverifiable/#w004',
  w005: 'unverifiable/#w005',
  w006: 'unverifiable/#w006',
  x001: 'crossfire/#x001',
  x002: 'crossfire/#x002',
  x003: 'crossfire/#x003',
  x004: 'crossfire/#x004',
  x005: 'crossfire/#x005',
  x006: 'crossfire/#x006',
  x007: 'crossfire/#x007',
  x008: 'crossfire/#x008',
  x009: 'crossfire/#x009',
  x010: 'crossfire/#x010',
  x011: 'crossfire/#x011',
  x012: 'crossfire/#x012',
  x013: 'crossfire/#x013',
  x014: 'crossfire/#x014',
  x015: 'crossfire/#x015',
  x016: 'crossfire/#x016',
  x017: 'crossfire/#x017',
  x018: 'crossfire/#x018',
  x019: 'crossfire/#x019',
  x020: 'crossfire/#x020',
  x021: 'crossfire/#x021',
  x022: 'crossfire/#x022',
  x023: 'crossfire/#x023',
  x024: 'crossfire/#x024',
  x025: 'crossfire/#x025',
}
/* rules-map:end */

export function ruleHref(id, base) {
  const page = RULE_PAGES[id.toLowerCase()]
  return page ? `${base}${page}` : null
}

/* Expand a range like "R141–R143" into its member ids ("R141", "R142",
   "R143"). Assumes a shared letter prefix and a numeric span of at most 99. */
function rangeIds(a, b) {
  const prefix = a[0]
  const start = Number(a.slice(1))
  const end = Number(b.slice(1))
  if (end < start || end - start > 99) return null
  const out = []
  for (let n = start; n <= end; n += 1) out.push(`${prefix}${String(n).padStart(3, '0')}`)
  return out
}

/* Turn rule mentions inside an HTML string into links to their doc pages.
   Ranges ("S001–S008") become one link to the category page when every rule
   in the range lives on it, or per-rule links when the range crosses pages.
   Single ids link straight to their anchor. Everything else passes through. */
export function linkRules(html, base) {
  return html.replace(/([RCDSXPW]\d{3})–([RCDSXPW]\d{3})|([RCDSXPW]\d{3})/g, (m, ra, rb, single) => {
    if (ra && rb) {
      const ids = rangeIds(ra, rb)
      if (!ids) return m
      const hrefs = ids.map((id) => ruleHref(id, base))
      const known = hrefs.filter(Boolean)
      const first = known[0]
      const allSamePage = first && known.every((href) => href.split('#')[0] === first.split('#')[0])
      if (allSamePage) {
        // Same category page: one link. If every id resolves to the exact
        // same anchor (e.g. the P rules all under #declared-practice, with
        // the skipped P004 falling out of the map) keep the anchor, otherwise
        // link the whole range to the category page.
        const allIdentical = known.every((href) => href === first)
        const target = allIdentical ? first : first.split('#')[0]
        return `<a href="${target}" target="_blank" rel="noreferrer">${m}</a>`
      }
      // The range crosses category pages (R141–R143): one link per rule.
      return ids
        .map((id, i) => {
          const href = hrefs[i]
          return href ? `<a href="${href}" target="_blank" rel="noreferrer">${id}</a>` : id
        })
        .join('–')
    }
    const href = ruleHref(single, base)
    return href ? `<a href="${href}" target="_blank" rel="noreferrer">${single}</a>` : m
  })
}
